### ISSUE TITLE
Coinbase Portfolio Gains

### ISSUE THREAD

**Issue by goblej216** [kevduc/userscripts#3]
It looks like there's a problem with this script it's no longer working on the dashboard or accounts page.  I didn't really look much more into it.  I love the script though!

**Comment by kevduc** [comment]
Hi @goblej216,

Thanks for reporting this, I've just updated the script with a fix that should work.
You can click on this link [CoinbasePortfolioGains.user.js](https://raw.githubusercontent.com/kevduc/userscripts/master/CoinbasePortfolioGains.user.js) to update your script.
Let me know if there's any other issue.

Thanks!
Kevin

**Comment by kevduc** [comment]
Fixed by https://github.com/kevduc/userscripts/commit/7ab25f71671f01697f922f5b55cd43f397adfc7d
